coding_task:
  description: >
    Write python code to achieve this: {assignment}
  expected_output: >
    A text file that includes the code itself, along with the output of the code.
  agent: coder
  output_file: output/code_and_output.txt

scaffold_task:
  description: >
    Scaffold a new {framework} web application named {project_name} under the folder {target_root}.
    Use TypeScript: {typescript}. Use Tailwind: {tailwind}. Preferred package manager: {package_manager}.
    Choose the appropriate tool: NextJsScaffoldTool for Next.js or ReactViteScaffoldTool for React.
    After scaffolding, list the created files and provide follow-up commands to run the app.
  expected_output: >
    A short report describing the generated project location and the commands to install and run it, plus a file tree summary.
  agent: web_scaffolder
  output_file: output/scaffold_report.txt